FUNCTION ZF18_SET_SY_TABLE.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IV_PO) TYPE  CHAR1 OPTIONAL
*"     VALUE(IV_SO) TYPE  CHAR1 OPTIONAL
*"     VALUE(IV_DO) TYPE  CHAR1 OPTIONAL
*"     VALUE(IV_BI) TYPE  CHAR1 OPTIONAL
*"  EXPORTING
*"     REFERENCE(ES_RETURN) TYPE  BAPIRET2
*"----------------------------------------------------------------------



" IV_PO 가 있을 경우!!
IF IV_PO IS NOT INITIAL.

  " 이런식으로 IF 문 안에다가 선언을 해도 되는지 모르겠지만
  " 데이터 선언을 많이 하면, 메모리를 많이 차지할 것 같아서, IF문 안에 넣어보았습니다.

  DATA: GT_ZEKKO18 TYPE TABLE OF ZEKKO18.
  DATA: GT_ZEKPO18 TYPE TABLE OF ZEKPO18.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_ZEKKO18  " 인터널 테이블에 데이터 넣기
    FROM EKKO.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_ZEKPO18
    FROM EKPO.

  " if GT_ZEKKO18 IS NO INITIAL 문을 안한 이유는,
  " 값이 없을 경우는 별로 없을 것 같고,
  " 그런데 계속 확인하면, 시스템 자원을 좀 먹을 것 같아서 입니다.
  MODIFY ZEKKO18 FROM TABLE GT_ZEKKO18.   " 인터널테이블 -> 테이블
  MODIFY ZEKPO18 FROM TABLE GT_ZEKPO18.


  ES_RETURN-TYPE = ZLEA_S.  " 성공 시 'S' 넣기   // 이거는 마지막에 판단하기

ENDIF.

" IV_SO 가 있을 경우!!
IF IV_SO IS NOT INITIAL.

  DATA: GT_ZVBAK18 TYPE TABLE OF ZVBAK18.
  DATA: GT_ZVBAP18 TYPE TABLE OF ZVBAP18.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_ZVBAK18
    FROM VBAK.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_ZVBAP18
    FROM VBAP.

  MODIFY ZVBAK18 FROM TABLE GT_ZVBAK18.
  MODIFY ZVBAP18 FROM TABLE GT_ZVBAP18.

  ES_RETURN-TYPE = ZLEA_S.

ENDIF.


" IV_DO 가 있을 경우!!
IF IV_DO IS NOT INITIAL.

  DATA: GT_ZLIKP18 TYPE TABLE OF ZLIKP18.
  DATA: GT_ZLIPS18 TYPE TABLE OF ZLIPS18.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_ZLIKP18
    FROM LIKP.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_ZLIPS18
    FROM LIPS.

  MODIFY ZLIKP18 FROM TABLE GT_ZLIKP18.
  MODIFY ZLIPS18 FROM TABLE GT_ZLIPS18.

  ES_RETURN-TYPE = ZLEA_S.

ENDIF.


" IV_BI 가 있는 경우!!
IF IV_BI IS NOT INITIAL.

  DATA: GT_ZVBRK18 TYPE TABLE OF ZVBRK18.
  DATA: GT_ZVBRP18 TYPE TABLE OF ZVBRP18.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_ZVBRK18
    FROM VBRK.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_ZVBRP18
    FROM VBRP.

  MODIFY ZVBRK18 FROM TABLE GT_ZVBRK18.
  MODIFY ZVBRP18 FROM TABLE GT_ZVBRP18.

  ES_RETURN-TYPE = ZLEA_S.

ENDIF.



IF ES_RETURN-TYPE IS INITIAL.   " ES_RETURN-TYPE 이 처음 값이면. 모든 파라메터(IV_PO, ... , IV_BI)가 비었다는 뜻.
  ES_RETURN-TYPE = ZLEA_E.
  ES_RETURN-MESSAGE = 'There is no data to process.'.
ELSE.
  ES_RETURN-MESSAGE = 'It is saved'.
ENDIF.

" 서브 루틴 활용하기에는 어려워보이네요 ㅠ
*FORM SV_TABLE CHANGING PS_ITAB.
*
**  SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_ZEKKO18
**    FROM EKKO.
*
*ENDFORM.


ENDFUNCTION.
